# Generated by Django 4.1.6 on 2023-03-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_valve',
            new_name='variation_value',
        ),
    ]
